version: "3.8"

services:
  postgres_main:
    image: postgres:13-alpine
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword

volumes:
  postgres_data:
